# Machine Learning - Detect types of Iris Plant
Resources:
- Scikit learn: https://scikit-learn.org/stable/
- Iris Dataset: https://en.wikipedia.org/wiki/Iris_flower_data_set

In [2]:
from sklearn.datasets import load_iris
iris = load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

## 3. SPLIT DATA - TRAINING SET/TEST SET
Assuming the iris datasets are clean, this will mainly focus on 
the data-science/ machine learning training

### X AND Y CONCEPTS 
In machine learning there are common concepts to keep in mind
- X and Y concepts
	- `X` variable is for input file
	- `Y` variable is for targets

Note:
Here, as the datasets are correctly labelled,  the first step is to get familiar with the data set

In [17]:
# MACHINE LEARNING X AND Y CONCEPTS
X = iris.data
Y = iris.target

# values in target ( Y )  0,1,2 :represent the types of iris plant
print(f"""
'X' AS INPUT PREVIEW:
{X[:5]}
--> Type X: {type(X)}

'Y' AS TARGET PREVIEW:
{Y}
--> Type Y: {type(Y)}
""")


'X' AS INPUT PREVIEW:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
--> Type X: <class 'numpy.ndarray'>

'Y' AS TARGET PREVIEW:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
--> Type Y: <class 'numpy.ndarray'>



In [18]:
# OBJECTIVE:
# Find or Create a function to take the input which should output y

feature_names = iris.feature_names
target_names = iris.target_names

print(f"""
	IRIS FEATURE NAMES:
	{feature_names}

	TARGET FEATURE NAMES:
	{target_names}
""")


	IRIS FEATURE NAMES:
	['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

	TARGET FEATURE NAMES:
	['setosa' 'versicolor' 'virginica']



### SPLIT DATA: TRAINING SET AND TESTING SET
Use `sklearn.model_selection.train_test_split` to split arrays or matrices into random train and test subsets
In this method we could provide how much percent do we want to do test with the parameter named 
`test_size` accepting a floating number

In [25]:
from sklearn.model_selection import train_test_split
# test_size argument refers to percentage of the amount of test
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)

print(f"""
	X_train shape:
	{X_train.shape}

	X_test shape:
	{X_test.shape}

	Y_train shape:
	{Y_train.shape}

	Y_test shape:
	{Y_test.shape}
""")


	X_train shape:
	(120, 4)

	X_test shape:
	(30, 4)

	Y_train shape:
	(120,)

	Y_test shape:
	(30,)



## 4. CREATE A MODEL
From the third step ( split data into training and testing set ),
those elements will help in creating a model with nearest Nearest Neighbor Classification algorithm 
which will help in dividing the data into different sets
_Note: One of the job of a machine learning engineer is to figure out which algorithm to use_
`sklearn.neighbors.KNeighborsClassifier`

Resources:
- Nearest Neighbor: https://scikit-learn.org/stable/modules/neighbors.html

Extra Resources:
- KNearestNeighbors: http://vision.stanford.edu/teaching/cs231n-demos/knn/
- Algorithm: https://www.analyticsvidhya.com/blog/2018/08/k-nearest-neighbor-introduction-regression-python/


In [33]:
from sklearn.neighbors import KNeighborsClassifier

# ------------------------------- CREATE MODEL ------------------------------- #

# instantiate the KNeighborsClassifier with n_neighbors around to observe
# in order to observe and decide which type of flower one data is
kn = KNeighborsClassifier(n_neighbors=3)

kn.fit(X_train, Y_train)



# -------------------------------- CHECK MODEL ------------------------------- #

# What the model predict for y based on X_test data
y_pred = kn.predict(X_test)

# Compares model prediction ( y_pred ) with splitted tests
from sklearn import metrics
test_accuracy = metrics.accuracy_score(Y_test, y_pred)

print(f"""
	Predict accuracy result ( Y_test vs Prediction result ):
		--> {test_accuracy * 100 } %
""")


	Predict accuracy result ( Y_test vs Prediction result ):
		--> 96.66666666666667 %



/Users/laurelineparis/opt/anaconda3/lib/python3.9/site-packages/sklearn/neighbors/_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


# 5. IMPROVING THE MODEL
Improving the data implies :
- the amount `test_size` value for the `sklearn.model_selection.split()` method
This is anticipated on the amount of data we have as inputs
- features == columns to observe / predict from --> the more we have --> the more the model prediction
would be more accurate
- algorithm used: explore different algorithm

In [34]:
# ---------------------------------- IMPROVE --------------------------------- #
# Re-define the amount of training and test to have more data to examine
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)
print(f"""
	X_train shape:
	{X_train.shape}

	X_test shape:
	{X_test.shape}

	Y_train shape:
	{Y_train.shape}

	Y_test shape:
	{Y_test.shape}
""")


	X_train shape:
	(120, 4)

	X_test shape:
	(30, 4)

	Y_train shape:
	(120,)

	Y_test shape:
	(30,)



In [36]:
from sklearn.tree import DecisionTreeClassifier

# kn = KNeighborsClassifier(n_neighbors=3)
kn = DecisionTreeClassifier()
kn.fit(X_train, Y_train)
y_pred = kn.predict(X_test)
test_accuracy = metrics.accuracy_score(Y_test, y_pred)

print(f"""
	2nd Predict accuracy result ( Y_test vs Prediction result ):
		--> {test_accuracy * 100 } %
""")


	2nd Predict accuracy result ( Y_test vs Prediction result ):
		--> 93.33333333333333 %



We can observe that the test_size with, 0.2 was more accurate with KNneighborsClassifier than DecisionTreeClassifier

### MORE ACCURACY DEEPENING
Knowing the shape of an iris, we could also provide a emulated flower ( a list of x floats )
to test what could be the type of flower 


In [45]:
sample = [
	[2.3, 2.1, 0.2, 1.1],
	[0.3, 1.3, 0.2, 9.1]
	]
predictions = kn.predict(sample)
pred_species = [iris.target_names[x] for x in predictions]
print(f"""
	Sample predictions type:
		--> {pred_species }
""")


	Sample predictions type:
		--> ['versicolor', 'virginica']



## MODEL PERSISTANCE
In real life, to train a real complex model are time consuming + power consuming.
Real datasets are way much bigger: sometimes a regular computer would takes time or would not being able to handle the amount of data to predict. ( through the `fit` method ) The solution would be to use the cloud to handle them
( Sometimes an engineer has to process this on a GPU or graphical processing unit )
This is called model persistance

This allows to re use the model in a saved file.
Objective: Persisting the model to a cloud

Resource:
- https://scikit-learn.org/stable/modules/model_persistence.html

Note about joblib:
- Course uses an older way to import it `from sklearn.externals import joblib`
- Use `from joblib import dump, load`

In [47]:
from joblib import dump, load

file_name = 'mliris.joblib'

# Saving model
dump(kn, file_name)

# Using saved model
model = load(file_name)
model.predict(X_test)

array([1, 2, 1, 0, 2, 0, 0, 1, 1, 2, 2, 0, 2, 1, 2, 1, 0, 1, 0, 2, 2, 0,
       2, 2, 2, 2, 2, 2, 0, 1])

Courses Iris notebook: https://github.com/aneagoie/ML-Notes/blob/master/iris.ipynb